<?php

namespace SkyEng\Request;


use SkyEng\Response\JsonDataResponse;

class JsonDataRequest extends DataRequest
{
    /** @var string */
    protected $responseClass = JsonDataResponse::class;

    public function __construct(String $host)
    {
        parent::__construct($host);

        $this->setMethod(self::METHOD_POST)
             ->setHeader('Content-Type', 'application/json');
    }

    /**
     * @param Mixed $content
     * @return DataRequest
     */
    public function setJsonContent($content)
    {
        return parent::setContent(json_encode($content)); // TODO: Change the autogenerated stub
    }
}